### PR TITLE
Updated to api version 0.2.1

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by rdallman** [comment]
i believe there is a script to generate all of the libraries `fn_$lang` and update them, I don't see any other libraries update but this one. I'm gonna try to dig this thing up, maybe @treeder can point it out if he's around.

**Comment by denismakogon** [comment]
I am aware of that script, I’m using it to generate clients. At this moment I generated only fn_go

**Comment by rdallman** [comment]
can you update all so that they're in sync, please? looks like it will push and everything https://github.com/fnproject/fn/tree/master/clients -- were there issues trying this?

**Comment by rdallman** [comment]
also seems like this didn't do version bump as last commit here had same version https://github.com/fnproject/fn_go/commit/418dcd8e37593d86604e89a48d7ee2e109a1d3bf

**Comment by denismakogon** [comment]
@treeder

**Pull request closed without merging**
