### PR TITLE
Move authentication and providers from CLI into SDK

### PR DESCRIPTION
**Pull request by zootalures**
Abstracts providers behind an interface - allows code other than the SDK to use the OCI/HTTP signing auth provider  (e.g. in testing) 

Corresponding CLI WIP change is here: https://github.com/fnproject/cli/pull/298

### CODE REVIEW

**Comment by zootalures** [comment]
Don't think that autogeneration will cause merge issues - as only `client` and `models` are  touched   by go-swagger.

**Comment by zootalures** [comment]
Agree it's a bit shonky mind you but couldn't think of a reason why it's outright wrong - got any better ideas?

**Comment by zootalures** [comment]
Yeah - thought about that - I think given that you almost certainly want  a provider implementation to use the SDK it made more sense to bundle the initial set that we have into the same repo initially -  if we end up having lots with lots of dependencies then yes - it make sense to split - but now that felt a bit too fine grained (e.g. default provider is < 100 LoC) 

From a client point of view (e.g in the CLI)  you end up importing all of the supported providers anyway so it made sense for the SDK to mediate those for you.  - Given that the oracle dep doesn't add too much in the way of dependencies i figured leaving this here made sense. 

The extnension conract here lets people hook in other providers from other repos anyway so any non-fn derrived provdiers can still be added.

**Comment by rdallman** [comment]
I gave this a think and my unsolicited $.02 is it seems ok to put these in each SDK (I also knee jerked, prior to said think). Makes sense to put them in SDK since we probably want various languages to support each provider, so that users can use the SDK against various services (not just cli). Assuming that we may implement these in various languages (SDKs for each lang) it is probably better than having a providers repo  that has by provider -> by lang or by lang -> by provider or a providers repo for each lang [or a repo per lang per provider]. I'm not sure if any of these sound more appealing to anyone else, my thinking is no. Also, yea as long as we can tax free keep generating clients this isn't that big of a concern, so +1 and $.02 from me

**Comment by zootalures** [comment]
Any thoughts on the provider interface itself? - I feel like I went back and forth until I had something that worked but not something I was particularly happy with.

**Comment by rdallman** [comment]
wrap transport is pretty sensible interface wise, decorating `http.RoundTripper` is pretty standard and is clean. another way I've seen is https://golang.org/pkg/net/http/httputil/#ReverseProxy where they just let you pass in a function that modifies the request - maybe this would be easier to implement, I'm not sure - I guess you could pass a function of that sort to the constructor of an SDK client struct.

**Pull request merged**
